-- INSERT INTO status(id)
-- VALUES (1)
-- WHERE NOT EXISTS (
--     SELECT id FROM status WHERE id=1;
-- );
-- INSERT INTO status(id)
-- VALUES (2)
-- WHERE NOT EXISTS (
--     SELECT id FROM status WHERE id=2;
-- );